<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MajorModel extends Model
{
    public static $Major = [
        ['facultyID'=>'1','majorID'=>'ENG01','majorNameTH' => null,'majorNameEN' => 'Biomedical Engineer'],
        ['facultyID'=>'1','majorID'=>'ENG02','majorNameTH' => null,'majorNameEN' => 'Computer Engineering'],
        ['facultyID'=>'1','majorID'=>'ENG03','majorNameTH' => null,'majorNameEN' => 'Mechanical Engineering'],
        ['facultyID'=>'1','majorID'=>'ENG04','majorNameTH' => null,'majorNameEN' => 'Chemical Engineering'],
        ['facultyID'=>'1','majorID'=>'ENG05','majorNameTH' => null,'majorNameEN' => 'Civil Engineering'],
        ['facultyID'=>'1','majorID'=>'ENG06','majorNameTH' => null,'majorNameEN' => 'Industrial Engineering'],
        ['facultyID'=>'1','majorID'=>'ENG07','majorNameTH' => null,'majorNameEN' => 'Multidisciplinary Engineering'],
        ['facultyID'=>'1','majorID'=>'ENG08','majorNameTH' => 'วิศวกรรมชีวการแพทย์ & แพทยศาสตรบัณฑิต'],
        ['facultyID'=>'1','majorID'=>'ENG09','majorNameEN' => 'Bachelor of Engineering in Smart Materials Technology & Bachelor of Engineering in Robotics and AI Engineering'],
        ['facultyID'=>'1','majorID'=>'ENG10','majorNameTH' => 'วิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมระบบไอโอทีและสารสนเทศ & วิทยาศาสตรบัณฑิต สาขาวิชาฟิสิกส์อุตสาหกรรม','majorNameEN' =>null],
        ['facultyID'=>'1','majorID'=>'ENG11','majorNameTH' => 'วิทยาศาสตรบัณฑิต สาขาวิชาวิศวกรรมแปรรูปอาหาร & วิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมอุตสาหการ','majorNameEN' =>null],
        ['facultyID'=>'1','majorID'=>'ENG12','majorNameTH' => 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมโยธา) & วิทยาศาสตรบัณฑิต(สถาปัตยกรรม)','majorNameEN' =>null],
        ['facultyID'=>'1','majorID'=>'ENG13','majorNameTH' => 'วิศวกรรมการวัดและควบคุม','majorNameEN' =>null],
        ['facultyID'=>'1','majorID'=>'ENG14','majorNameTH' => 'วิศวกรรมคอมพิวเตอร์','majorNameEN' =>null],
        ['facultyID'=>'1','majorID'=>'ENG15','majorNameTH' => 'วิศวกรรมเครื่องกล','majorNameEN' =>null],
        ['facultyID'=>'1','majorID'=>'ENG16','majorNameTH' => 'วิศวกรรมเคมี','majorNameEN' =>null],
        ['facultyID'=>'1','majorID'=>'ENG17','majorNameTH' => 'วิศวกรรมไฟฟ้า','majorNameEN' =>null],
        ['facultyID'=>'1','majorID'=>'ENG18','majorNameTH' => 'วิศวกรรมอุตสาหการ','majorNameEN' =>null],
        ['facultyID'=>'1','majorID'=>'ENG19','majorNameTH' => 'วิศวกรรมอาหาร','majorNameEN' =>null],
        ['facultyID'=>'1','majorID'=>'ENG20','majorNameTH' => 'วิศวกรรมอิเล็กทรอนิกส์','majorNameEN' =>null],
        ['facultyID'=>'1','majorID'=>'ENG21','majorNameTH' => 'วิศวกรรมโทรคมนาคม','majorNameEN' =>null],
        ['facultyID'=>'1','majorID'=>'ENG22','majorNameTH' => 'วิศวกรรมโยธา','majorNameEN' =>null],
        ['facultyID'=>'1','majorID'=>'ENG23','majorNameTH' => 'วิศวกรรมเกษตร','majorNameEN' =>null],
        ['facultyID'=>'2','majorID'=>'ARC01','majorNameTH' => null,'majorNameEN' =>'Bachelor of Science in Architecture'],
        ['facultyID'=>'2','majorID'=>'ARC02','majorNameTH' => null,'majorNameEN' =>'Bachelor of Fine Arts in Creative Arts and Curatorial Studies'],
        ['facultyID'=>'2','majorID'=>'ARC03','majorNameTH' => null,'majorNameEN' =>'Bachelor of Design Program in Design Intelligence for Creative Economy (International Program)'],
        ['facultyID'=>'2','majorID'=>'ARC04','majorNameTH' => 'วิศวกรรมศาสตรบัณฑิต (วิศวกรรมโยธา) & วิทยาศาสตรบัณฑิต(สถาปัตยกรรม)','majorNameEN' =>null],
        ['facultyID'=>'2','majorID'=>'ARC05','majorNameTH' => 'สถาปัตยกรรม','majorNameEN' =>null],
        ['facultyID'=>'2','majorID'=>'ARC06','majorNameTH' => 'สถาปัตยกรรมภายใน','majorNameEN' =>null],
        ['facultyID'=>'2','majorID'=>'ARC07','majorNameTH' => 'ศิลปอุตสาหกรรม','majorNameEN' =>null],
        ['facultyID'=>'2','majorID'=>'ARC08','majorNameTH' => 'นิเทศศิลป์','majorNameEN' =>null],
        ['facultyID'=>'2','majorID'=>'ARC09','majorNameTH' => 'วิจิตรศิลป์','majorNameEN' =>null],
        ['facultyID'=>'2','majorID'=>'ARC10','majorNameTH' => 'ศิลปกรรม','majorNameEN' =>null],
        ['facultyID'=>'3','majorID'=>'EDU01','majorNameTH' => 'ครุศาสตร์สถาปัตยกรรม','majorNameEN' =>null],
        ['facultyID'=>'3','majorID'=>'EDU02','majorNameTH' => 'ครุศาสตร์วิศวกรรม','majorNameEN' =>null],
        ['facultyID'=>'3','majorID'=>'EDU03','majorNameTH' => 'ครุศาสตร์เกษตร','majorNameEN' =>null],
        ['facultyID'=>'3','majorID'=>'EDU04','majorNameTH' => 'ครุศาสตร์ภาษาและสังคม','majorNameEN' =>null],
        ['facultyID'=>'4','majorID'=>'AGR01','majorNameTH' => 'เทคโนโลยีการผลิตพืช','majorNameEN' =>null],
        ['facultyID'=>'4','majorID'=>'AGR02','majorNameTH' => 'เทคโนโลยีการผลิตสัตว์และประมง','majorNameEN' =>null],
        ['facultyID'=>'4','majorID'=>'AGR03','majorNameTH' => 'ปฐพีวิทยา','majorNameEN' =>null],
        ['facultyID'=>'4','majorID'=>'AGR04','majorNameTH' => 'เทคโนโลยีการจัดการศัตรูพืช','majorNameEN' =>null],
        ['facultyID'=>'4','majorID'=>'AGR05','majorNameTH' => 'นวัตกรรมการสื่อสารและพัฒนาการเกษตร','majorNameEN' =>null],
        ['facultyID'=>'4','majorID'=>'AGR06','majorNameTH' => 'สำนักงานบริหารหลักสูตรสหวิทยาการเทคโนโลยีการเกษตร','majorNameEN' =>null],
        ['facultyID'=>'5','majorID'=>'SCI01','majorNameTH' => 'คณิตศาสตร์','majorNameEN' =>null],
        ['facultyID'=>'5','majorID'=>'SCI02','majorNameTH' => 'วิทยาการคอมพิวเตอร์','majorNameEN' =>null],
        ['facultyID'=>'5','majorID'=>'SCI03','majorNameTH' => 'เคมี','majorNameEN' =>null],
        ['facultyID'=>'5','majorID'=>'SCI04','majorNameTH' => 'ชีววิทยา','majorNameEN' =>null],
        ['facultyID'=>'5','majorID'=>'SCI05','majorNameTH' => 'ฟิสิกส์','majorNameEN' =>null],
        ['facultyID'=>'5','majorID'=>'SCI06','majorNameTH' => 'สถิติ','majorNameEN' =>null],
        ['facultyID'=>'5','majorID'=>'SCI07','majorNameTH' => 'ศูนย์วิเคราะห์ข้อมูลดิจิทัลอัจฉริยะพระจอมเกล้าลาดกระบัง','majorNameEN' =>null],
        ['facultyID'=>'6','majorID'=>'INF01','majorNameTH' => 'เทคโนโลยีสารสนเทศ','majorNameEN' =>null],
        ['facultyID'=>'7','majorID'=>'FOO01','majorNameTH' => 'วิทยาศาสตรบัณฑิต สาขาวิชาวิศวกรรมแปรรูปอาหาร & วิศวกรรมศาสตรบัณฑิต สาขาวิชาวิศวกรรมอุตสาหการ','majorNameEN' =>null],
        ['facultyID'=>'7','majorID'=>'FOO02','majorNameTH' => 'อุตสาหกรรมอาหาร','majorNameEN' =>null],
        ['facultyID'=>'8','majorID'=>'NAN01','majorNameTH' => 'นาโนวิทยาและนาโนเทคโนโลยี ','majorNameEN' =>null],
        ['facultyID'=>'8','majorID'=>'NAN02','majorNameTH' =>  null,'majorNameEN' =>'Multidisciplinary'],
        ['facultyID'=>'8','majorID'=>'NAN03','majorNameTH' =>  'วิศวกรรมวัสดุนาโน & Polymer Materials and Engineering','majorNameEN' =>null],
        ['facultyID'=>'9','majorID'=>'ADV01','majorNameTH' =>  'วิศวกรรมระบบการผลิต','majorNameEN' =>null],
        ['facultyID'=>'10','majorID'=>'INT01','majorNameTH' => 'วิศวกรรมซอฟต์แวร์','majorNameEN' =>null],
        ['facultyID'=>'10','majorID'=>'INT02','majorNameTH' => 'การจัดการวิศวกรรมและเทคโนโลยี','majorNameEN' =>null],
        ['facultyID'=>'11','majorID'=>'BUS01','majorNameTH' => 'บริหารธุรกิจเกษตร','majorNameEN' =>null],
        ['facultyID'=>'11','majorID'=>'BUS02','majorNameTH' => 'บริหารธุรกิจ','majorNameEN' =>null],
        ['facultyID'=>'11','majorID'=>'BUS03','majorNameTH' => 'เศรษฐศาสตร์ธุรกิจและการจัดการ','majorNameEN' =>null],
        ['facultyID'=>'12','majorID'=>'LIB01','majorNameTH' => 'ศิลปศาสตร์ประยุกต์','majorNameEN' =>null],
        ['facultyID'=>'12','majorID'=>'LIB02','majorNameTH' => 'ภาษา','majorNameEN' =>null],
        ['facultyID'=>'12','majorID'=>'LIB03','majorNameTH' => 'มนุษยศาสตร์และสังคมศาสตร์','majorNameEN' =>null],
        ['facultyID'=>'13','majorID'=>'MED01','majorNameTH' => 'แพทยศาสตรนานาชาติ','majorNameEN' =>null],
        ['facultyID'=>'14','majorID'=>'MUS01','majorNameTH' => 'วิศวกรรมดนตรีและสื่อประสม','majorNameEN' =>null],
        ['facultyID'=>'15','majorID'=>'DEN01','majorNameTH' => 'ทันตแพทยศาสตร์ ','majorNameEN' =>'Dentistry'],
        ['facultyID'=>'16','majorID'=>'AIR01','majorNameTH' => 'วิศวกรรมเครื่องกล ','majorNameEN' =>null],
        ['facultyID'=>'16','majorID'=>'AIR02','majorNameTH' => 'วิศวกรรมการบิน ','majorNameEN' =>null],
        ['facultyID'=>'16','majorID'=>'AIR03','majorNameTH' => 'นวัตกรรมการจัดการอุตสาหกรรมการบินและการบริการ ','majorNameEN' =>null],

    ];

    use HasFactory;
}
